#ifndef __CONTROL_UINPUT_H
/* operands in passthrough commands */
#if 0
	SELECT_OP,
	UP_OP,
	DOWN_OP,
	LEFT_OP,
	RIGHT_OP,
	RIGHT_UP_OP,
	RIGHT_DOWN_OP,
	LEFT_UP_OP,
	LEFT_DOWN_OP,
	ROOT_MENU_OP,
	SETUP_MENU_OP,
	CONTENTS_MENU_OP,
	FAVORITE_MENU_OP,
	EXIT_OP,
	N0_OP,
	N1_OP,
	N2_OP,
	N3_OP,
	N4_OP,
	N5_OP,
	N6_OP,
	N7_OP,
	N8_OP,
	N9_OP,
	NDOT_OP,
	ENTER_OP,
	CLEAR_OP,
	CHANNEL_UP_OP,
	CHANNEL_DOWN_OP,
	PREV_CHANNEL_OP,
	SOUND_SELECT_OP,
	INPUT_SELECT_OP,
	DISPLAY_INFO_OP,
	HELP_OP,
	PAGE_UP_OP,
	PAGE_DOWN_OP,
	POWER_OP,
	VOL_UP_OP,
	VOL_DOWN_OP,
	MUTE_OP,
	PLAY_OP,
	STOP_OP,
	PAUSE_OP,
	RECORD_OP,
	REWIND_OP,
	FAST_FORWARD_OP,
	EJECT_OP,
	FORWARD_OP,
	BACKWARD_OP,
	ANGLE_OP,
	SUBPICTURE_OP,
	F1_OP,
	F2_OP,
	F3_OP,
	F4_OP,
	F5_OP,
#endif
#define VOL_UP_OP		0x41
#define VOL_DOWN_OP		0x42
#define MUTE_OP			0x43
#define PLAY_OP			0x44
#define STOP_OP			0x45
#define PAUSE_OP		0x46
#define RECORD_OP		0x47
#define REWIND_OP		0x48
#define FAST_FORWARD_OP		0x49
#define EJECT_OP		0x4a
#define FORWARD_OP		0x4b
#define BACKWARD_OP		0x4c

#define QUIRK_NO_RELEASE	1 << 0

extern struct control_plugin uinput_control_plugin;
#endif	/* __CONTROL_UINPUT_H */
